
use strict;
use warnings;

use Module::Build 0.3601;


my %module_build_args = (
  'build_requires' => {
    'File::Find' => '0',
    'File::Temp' => '0',
    'Module::Build' => '0.3601',
    'POSIX' => '0',
    'Test::More' => '0'
  },
  'configure_requires' => {
    'Module::Build' => '0.3601'
  },
  'dist_abstract' => 'Thread specific signal masks',
  'dist_author' => [
    'Leon Timmermans <leont@cpan.org>'
  ],
  'dist_name' => 'Thread-SigMask',
  'dist_version' => '0.003',
  'license' => 'perl',
  'module_name' => 'Thread::SigMask',
  'recommends' => {},
  'recursive_test_files' => 1,
  'requires' => {
    'Sub::Exporter' => '0',
    'XSLoader' => '0',
    'perl' => '5.008',
    'strict' => '0',
    'warnings' => '0'
  },
  'script_files' => []
);


my $build = Module::Build->new(%module_build_args);

$build->create_build_script;
