---
name: Thread-SigMask
version: 0.002
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Thread specific signal masks
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  ExtUtils::CBuilder: 0
  Module::Build: 0.28
  Test::More: 0
requires:
  Sub::Exporter: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.28
provides:
  Thread::SigMask:
    file: lib/Thread/SigMask.pm
    version: 0.002
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
